### ISSUE TITLE
Paths

### ISSUE THREAD

**Issue by nzoschke** [nzoschke/gomesh#1]
I'm not sure if the prototool config and folder structure reflects the optimal paths...

```yaml
generate:
  go_options:
    import_path: github.com/nzoschke/omgrpc/protos
```

And `gen/go/protos/...` feels a bit off.
